sudo: required
services:
  - docker

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - docker pull nginx
  - docker pull python:3
  - docker pull jwilder/docker-gen

script:
  - docker build -t jwilder/nginx-proxy:bats .
  - bats test